name: LRT2 Daily ML Forecasting

on:
  schedule:
    # Run daily at 8:00 PM UTC (4:00 AM Manila Time) to pre-populate predictions before train operations start
    - cron: '0 20 * * *'
  workflow_dispatch: # Allows manual trigger from the GitHub web UI

jobs:
  run-forecaster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # Speeds up execution by caching python packages

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      # Run model training & baseline forecast calculation
      - name: Run ML Training & Forecast
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: python "Analytics Layer/model training, testing and validation/train_and_validate.py"
